# Generated by Django 4.1 on 2022-08-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('fecha_nacimiento', models.DateField()),
                ('altura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pais_origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=64)),
                ('nombre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='familiares.familiares')),
            ],
        ),
    ]
